version: '2'

services:

  nginx:
   build: nginx
   ports:
    - "8080:80"
    - "443:443"
   depends_on:
    - backend
   volumes:
    - "./frontend:/www/data"

  backend:
    build: backend
    ports:
      - "3000:3000"
      - "56745:56745"
    environment:
      NODE_ENV: "development"
    entrypoint: ["npm", "run", "debug"]
    volumes:
      - "./backend:/src"
