version: '2'

services:

  nginx:
   build: nginx
   ports:
    - "8080:80"
    - "443:443"
   depends_on:
    - backend
   volumes:
     - "./frontend/public:/www/data"
     - "./frontend/conf:/etc/nginx/conf.d"
     - "~/private/loopbackdomain_com/ssl:/etc/ssl"
     - "~/private/loopbackdomain_com/well-known:/www/data/.well-known"

  backend:
    build: backend
    ports:
      - "3000:3000"
      - "56745:56745"
    environment:
      NODE_ENV: "development"
    entrypoint: ["npm", "run", "debug"]
    volumes:
      - "./backend:/src"
      - "~/private/loopbackdomain_com/applepay:/src/server/resources"
