version: '2'

services:

  nginx:
   build: nginx
   ports:
    - "${HTTP_PORT}:80"
    - "${HTTPS_PORT}:443"
   environment:
    - SERVER_NAME="${SERVER_NAME}"
   depends_on:
    - backend
   volumes:
     - "./frontend/public:/www/data"
     - "./frontend/conf/nginx:/etc/nginx/conf.d"
     - "${PRIVATE_DIR}/loopbackdomain_com/ssl:/etc/ssl"
     - "${PRIVATE_DIR}/loopbackdomain_com/well-known:/www/data/.well-known"
   command: /bin/bash -c "envsubst '\${SERVER_NAME}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && tail -100 /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  backend:
    build: backend
    entrypoint: ["npm", "start"]
    volumes:
      - "./backend:/src"
      - "${PRIVATE_DIR}/loopbackdomain_com/applepay:/src/server/resources"
