version: '2'

services:

  nginx:
   build: nginx
   ports:
    - "${HTTP_PORT}:80"
    - "${HTTPS_PORT}:443"
   depends_on:
    - backend
   volumes:
     - "./frontend/public:/www/data"
     - "./frontend/conf:/etc/nginx/conf.d"
     - "${PRIVATE_DIR}/loopbackdomain_com/ssl:/etc/ssl"
     - "${PRIVATE_DIR}/loopbackdomain_com/well-known:/www/data/.well-known"

  backend:
    build: backend
    entrypoint: ["npm", "start"]
    volumes:
      - "./backend:/src"
      - "${PRIVATE_DIR}/loopbackdomain_com/applepay:/src/server/resources"
